// This file is auto-generated by @hey-api/openapi-ts

export const $MessagePublic = {
    properties: {
        content: {
            type: 'string',
            title: 'Content'
        },
        sent_by: {
            allOf: [
                {
                    '$ref': '#/components/schemas/SentBy'
                }
            ],
            default: 'user'
        },
        id: {
            type: 'string',
            title: 'Id'
        },
        thread_id: {
            type: 'string',
            title: 'Thread Id'
        }
    },
    type: 'object',
    required: ['content', 'id', 'thread_id'],
    title: 'MessagePublic'
} as const;

export const $ResponseModel = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'ResponseModel'
} as const;

export const $SentBy = {
    type: 'string',
    enum: ['user', 'bot'],
    title: 'SentBy'
} as const;

export const $ThreadPublicWithMessages = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        id: {
            type: 'string',
            title: 'Id'
        },
        messages: {
            items: {
                '$ref': '#/components/schemas/MessagePublic'
            },
            type: 'array',
            title: 'Messages'
        }
    },
    type: 'object',
    required: ['title', 'id', 'messages'],
    title: 'ThreadPublicWithMessages'
} as const;