// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { RootGetResponse, MessagesMessagesGetResponse, FilesFilesGetResponse, DeleteFileFilesFileIdDeleteData, DeleteFileFilesFileIdDeleteResponse, ThreadsThreadsGetResponse, UploadFileUploadPostData, UploadFileUploadPostResponse } from './types.gen';

/**
 * Root
 * @returns ResponseModel Successful Response
 * @throws ApiError
 */
export const rootGet = (): CancelablePromise<RootGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/'
}); };

/**
 * Messages
 * @returns MessagePublic Successful Response
 * @throws ApiError
 */
export const messagesMessagesGet = (): CancelablePromise<MessagesMessagesGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/messages'
}); };

/**
 * Files
 * @returns FilePublic Successful Response
 * @throws ApiError
 */
export const filesFilesGet = (): CancelablePromise<FilesFilesGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/files'
}); };

/**
 * Delete File
 * @param data The data for the request.
 * @param data.fileId
 * @returns ResponseModel Successful Response
 * @throws ApiError
 */
export const deleteFileFilesFileIdDelete = (data: DeleteFileFilesFileIdDeleteData): CancelablePromise<DeleteFileFilesFileIdDeleteResponse> => { return __request(OpenAPI, {
    method: 'DELETE',
    url: '/files/{file_id}',
    path: {
        file_id: data.fileId
    },
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Threads
 * @returns ThreadPublicWithMessages Successful Response
 * @throws ApiError
 */
export const threadsThreadsGet = (): CancelablePromise<ThreadsThreadsGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/threads'
}); };

/**
 * Upload File
 * @param data The data for the request.
 * @param data.formData
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const uploadFileUploadPost = (data: UploadFileUploadPostData): CancelablePromise<UploadFileUploadPostResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/upload',
    formData: data.formData,
    mediaType: 'multipart/form-data',
    errors: {
        422: 'Validation Error'
    }
}); };