// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { RootGetResponse, MessagesMessagesGetResponse, ThreadsThreadsGetResponse } from './types.gen';

/**
 * Root
 * @returns ResponseModel Successful Response
 * @throws ApiError
 */
export const rootGet = (): CancelablePromise<RootGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/'
}); };

/**
 * Messages
 * @returns MessagePublic Successful Response
 * @throws ApiError
 */
export const messagesMessagesGet = (): CancelablePromise<MessagesMessagesGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/messages'
}); };

/**
 * Threads
 * @returns ThreadPublicWithMessages Successful Response
 * @throws ApiError
 */
export const threadsThreadsGet = (): CancelablePromise<ThreadsThreadsGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/threads'
}); };