// This file is auto-generated by @hey-api/openapi-ts

export type MessagePublic = {
    content: string;
    sent_by?: SentBy;
    id: string;
    thread_id: string;
};

export type ResponseModel = {
    message: string;
};

export type SentBy = 'user' | 'bot';

export type ThreadPublicWithMessages = {
    title: string;
    created_at?: string;
    id: string;
    messages: Array<MessagePublic>;
};

export type RootGetResponse = ResponseModel;

export type MessagesMessagesGetResponse = Array<MessagePublic>;

export type ThreadsThreadsGetResponse = Array<ThreadPublicWithMessages>;

export type $OpenApiTs = {
    '/': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseModel;
            };
        };
    };
    '/messages': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<MessagePublic>;
            };
        };
    };
    '/threads': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<ThreadPublicWithMessages>;
            };
        };
    };
};