"""Add message kind

Revision ID: 053dc8fd05d5
Revises: aec1026e7ef0
Create Date: 2024-05-25 10:09:54.088731

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "053dc8fd05d5"
down_revision = "aec1026e7ef0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message",
        sa.Column(
            "kind",
            sa.Enum("message", "tool_start", "tool_output", name="messagekind"),
            nullable=False,
            server_default="message",
        ),
    )
    op.add_column(
        "message",
        sa.Column("tool_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "tool_name")
    op.drop_column("message", "kind")
    # ### end Alembic commands ###
