"""Add sent_by

Revision ID: 469f2952759e
Revises: 162f7681c6d6
Create Date: 2024-05-22 13:54:34.074755

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '469f2952759e'
down_revision = '162f7681c6d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('sent_by', sa.Enum('user', 'bot', name='sentby'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'sent_by')
    # ### end Alembic commands ###
