services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data

  nominatim:
    environment:
      - PBF_URL=https://download.geofabrik.de/europe/poland/dolnoslaskie-latest.osm.pbf
    ports:
      - 8080:8080
    image: mediagis/nominatim:4.4
