version: "3.8"

services:
  meeting-service:
    image: meeting-service:latest
    build:
      context: ./meeting-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./meeting-service/.env
    networks:
      - app-network
    deploy:
      replicas: 1

  notification-service:
    image: notification-service:latest
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    env_file:
      - ./notification-service/.env
    networks:
      - app-network
    deploy:
      replicas: 2

  recording-service:
    image: recording-service:latest
    build:
      context: ./recording-service
      dockerfile: Dockerfile
    env_file:
      - ./recording-service/.env
    networks:
      - app-network
    deploy:
      replicas: 3

  summary-service:
    image: summary-service:latest
    build:
      context: ./summary-service
      dockerfile: Dockerfile
    env_file:
      - ./summary-service/.env
    ports:
      - "3003:3003"
    networks:
      - app-network
    deploy:
      replicas: 1

  transcription-service:
    image: transcription-service:latest
    build:
      context: ./transcription-service
      dockerfile: Dockerfile
    env_file:
      - ./transcription-service/.env
    networks:
      - app-network
    deploy:
      replicas: 4

networks:
  app-network:
    driver: overlay
    attachable: true
